### ISSUE TITLE
Better documentation

### ISSUE THREAD

**Issue by JoNilsson** [jsphuebner/esp8266-web-interface#1]
This looks really interesting, but lacks any documentation for implementation.

**Comment by jsphuebner** [comment]
Indeed.
Do you want to contribute that?

**Comment by Berdi0305** [comment]
Hello Johannes !!!  I want to make my modest contribution !!

**Comment by catphish** [comment]
In the spirit of better documentation, I have started documentation of the standardized parts of the serial protocol: https://github.com/catphish/esp8266-web-interface/blob/master/PROTOCOL.md
