### ISSUE TITLE
Adding build instructions and reworking file layout

### ISSUE THREAD

**Issue by llange** [jsphuebner/esp8266-web-interface#13]
While I spent some time compiling and flashing the interface, I took some notes and thought I could share them.

Would you be open to a few changes regarding the project documentation and layout ?

My layout proposal would be:
* `/` (project level / git root)
  * `README.md`, `.gitignore`
  * `platformio.ini`, `Makefile`s and all build tooling
  * `FSBrowser/` <- new subdir of `/` in which we have the `FSBrowser.ino` file
    * `FSBrowser.ino` <- main C++ file
    * `data/` <- new subdir of `/FSBrowser/` in which we have all the web files for filesystem upload, no more, no less
      * `*css`, `*js`, `*html`, `*gif`, `*png`, `*.js.gz` 

I would add some info to the README.md files regarding building and uploading (code + filesystem) to the target. I would document both the standard Arduino IDE and the command-line platform.IO tooling which I'm using.

In addition I plan to explore the use of GitHub Actions to propose an automatic build workflow that could in a first step automatically build the project at each commit / tag and try to historize some of the automatically built releases in the "Releases" part of this GitHub repo.

Plus some of the (very small) changes for the code I have made, like having a debug compile-time option to debug on the serial port ; some changes around the mDNS identifier ; some config file for storing WiFi parameters for first use.

If you are OK with the proposal I'll start to submit some PRs for those.

Thanks for the feedback !

**Comment by jsphuebner** [comment]
good suggestions, actually I have most of them done locally. Wouldn't do the FSBrowser part but simply rename the ino file to esp8266-web-interface.ino

**Comment by llange** [comment]
Thanks @jsphuebner for your feedback !
Accordingly, I've reworked the layout, you can have a look at the final result here : https://github.com/llange/esp8266-web-interface/tree/fix-wrong-mdns-name

If it's OK for you then I'll open a few PRs for that.

**Comment by llange** [comment]
I just submitted the first of the PRs (#14 ) and will submit the other afterwards.

I split the PRs (and commits) by coherent units so that they can be reviewed accordingly.

**Comment by llange** [comment]
Now #16  is ready for review also.
 If you don't know (yet) [PlatformIO](https://platformio.org/) I suggest that you have a look at it if you want to script or automate your builds ; it works with Arduino but other Framework, OSes, etc... ; supports multiple boards / cpus / compilers / etc... and is a solid base for reproducibility of builds (you can pin the version of the libraries of course, but also the compilers, frameworks, etc...)

#17 and #18 will follow afterwards.

**Comment by llange** [comment]
Thanks @jsphuebner for merging #16 .

Now #17 is ready ; and after that #18 will follow.

**Comment by llange** [comment]
Thanks @jsphuebner for merging #17 !
My last one (#18) is a helper shell to upload the web interface HTML files without having to remember the `curl` command. Can be helpful, but not that important. You'll judge.

**Comment by llange** [comment]
Everything merged, thank you !
Closing this issue now.
