### ISSUE TITLE
WiFi Configuration

### ISSUE THREAD

**Issue by catphish** [jsphuebner/esp8266-web-interface#8]
I've just flashed the latest version of the Arduino sketch to a MOD-WIFI-ESP-8266. For a long time it appeared that the WiFi wasn't working. Eventually I realised this comes down to two issues:

1) There is no DHCP.
2) WiFi configuration set using the web interface does not see to persist to flash.

It seems to me that people don't use station mode, and it might be better to run the device in permanent AP mode with DHCP, and allow only the SSID and passphrase to be (persistently) set.

The versions of this web interface that ship with Tesla boards seem to have password protected WiFi networks and DHCP. Is there some code somewhere that I'm missing?

**Comment by catphish** [comment]
For my own use I have simply removed the wifi configuration interface and replaced the init code with a hardcoded SoftAP call, however the approach used by Damien here, storing the details in a file, would likely be the better option:

https://github.com/damienmaguire/Lexus-GS450H-Inverter-Controller/blob/master/WiFi/GS450H_WiFi_V1.ino#L113

**Comment by jsphuebner** [comment]
I'm starting to think it has to do with the Arduino libs. I am flashing a binary I compiled ages ago that tested fine. I will check the library for changes, maybe there is some new function call like Wifi.saveCreds() or so

**Comment by dimecho** [comment]
@catphish Check "Erase Flash" settings when flashing.

![arduino-eraseflash](https://user-images.githubusercontent.com/4879613/144656215-620af868-b435-48b8-a8e7-6b05ac5c86b8.png)

**Comment by catphish** [comment]
If this code worked before and now doesn't I strongly suspect the problem is explained here: https://arduino-esp8266.readthedocs.io/en/latest/esp8266wifi/generic-class.html#persistent

> Starting from version 3 of this core, persistence is disabled by default and WiFi does not start automatically at boot (see PR #7902).
> Legacy behavior can be restored by calling enableWiFiAtBootTime() from anywhere in the code (it is a weak void function intended to play with the linker).
> When legacy behavior is restored thanks to this call, ESP8266 is able to reconnect to the last used WiFi network or establishes the same Access Point upon power up or reset.

I'll give it a try at some point.

**Comment by catphish** [comment]
I think this would benefit from being combined with some code that detects if wifi is not yet configured, and sets up a default access point (rather than the current approach, which seems to always try to switch to client mode during setup(), then back to AP mode when client mode fails).

I'll work on it and see if I can build something that works reliable with current libraries.

**Comment by jsphuebner** [comment]
Good find!
Current behaviour is to enable BOTH AP and client mode and then disable client mode if it can't connect. Otherwise it lags from the connection attempts.

**Comment by damienmaguire** [comment]
Fix : 
void setup(void){
  #ifdef WIFI_IS_OFF_AT_BOOT
    enableWiFiAtBootTime(); // can be called from anywhere with the same effect
  #endif

as per : https://openinverter.org/forum/viewtopic.php?f=5&t=2001&p=35189#p35189

**Comment by catphish** [comment]
Looks like @dimecho already fixed this in 7e2447ecda8fcfc54dfca1138418034e518f4671 and Johannes merged it so I'll close this issue. Thanks all :+1:
