### ISSUE TITLE
Burst length off by one

### ISSUE THREAD

**Issue by catphish** [jsphuebner/esp8266-web-interface#9]
When using the charting function, or the logger, the burst length is off by one. For example, when requesting a burst length of 10, the HTTP request includes `repeat=10` however this makes 11 requests, not 10.

When using the data logger, this causes the average to be calculated incorrectly. For example, if you request a data item with a constant value of 1, and a burst length of 10, the average will be calculated at 1.1, because it receives 11 values, and divides the total by 10.

NB. This occurs when using the legacy "get" API, not the "stream" API.

**Comment by jsphuebner** [comment]
Well spotted but indeed not relevant anymore. The "get" API was superseded 5 years ago or so.

**Comment by catphish** [comment]
I implemented the `get` API in my new GS450H firmware, for now, because it allows me to maintain a simple event driven setup, with the web interface requesting the data, as opposed to the `stream` API which requires more complex state in in the inverter to periodically return values and not accept other commands in the meantime. I realise this isn't your problem, but for now I will fix the bug rather than worry about `stream`. Patch to follow.

**Comment by jsphuebner** [comment]
Oh, now I see what you're doing!
